[package]
name = "gw2fashionista-core"
version = "0.2.1"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
bon = "3.10.0"
chrono = "0.4.45"
gw2fashionista-appearance = { version = "0.1.0", path = "../appearance" }
gw2fashionista-chatlink = { version = "0.1.0", path = "../chatlink" }
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["macros", "sync", "time"] }
uuid = { version = "1.24.0", features = ["serde", "v7"] }

[dependencies.tracing]
version = "0.1.44"
optional = true

[dev-dependencies]
gw2fashionista-fixtures = { version = "0.1.0", path = "../fixtures" }
mockall = "0.15.0"
test-log = { version = "0.2.21", default-features = false, features = ["trace"] }
tokio = { version = "1.52.3", features = ["test-util", "rt-multi-thread"] }

[features]
default = ["tracing"]
tracing = ["dep:tracing"]
