# Pikku Tähti
# Armor only
tahti_armor_only = '[&DwAAGTMRBo0GjQYRBvc1EQaNBo0GEQZWKI0GEQYBABEG6zWNBhEGjQYRBo4ljQYRBhEGkgK6M40GjQYRBhEGoRaNBhEGAQABAAAAAQABAAEAAQAAAAAAAAAAAAAAAAD/fw==]'
# Hide outfit
tahti_hide_outfit = '[&D1oDGTMRBo0GjQYRBvc1EQaNBo0GEQZWKI0GEQYBABEG6zWNBhEGjQYRBo4ljQYRBhEGkgK6M40GjQYRBhEGoRaNBhEGAQABADIAAQABAAEAAQBoEqAPLjIAAC8yNzL/fg==]'
# Show all
tahti_show_all = '[&D1oDGTMRBo0GjQYRBvc1EQaNBo0GEQZWKI0GEQYBABEG6zWNBhEGjQYRBo4ljQYRBhEGkgK6M40GjQYRBhEGoRaNBhEGAQABADIAAQABAAEAAQBoEqAPLjIAAC8yNzL/fw==]'
# Hide all
tahti_hide_all = '[&D1oDGTMRBo0GjQYRBvc1EQaNBo0GEQZWKI0GEQYBABEG6zWNBhEGjQYRBo4ljQYRBhEGkgK6M40GjQYRBhEGoRaNBhEGAQABADIAAQABAAEAAQBoEqAPLjIAAC8yNzJMEA==]'

# Pikku Peekaboo
peekaboo = '[&D7UfzTMeBQYA4gQGAJ4AHgUGAB4FAQCsAAYABgAeBQEANSgBAAYAHgUBAMkDHgUGAAEAAQDVAAYAHgUeBQEAoRYeBQYAAQABADIAAQABAAEAAQBoEqAPFCovKj8SAAD/fg==]'
# Armor only
peekaboo_armor_only = '[&D7UfzTMeBQYA4gQGAJ4AHgUGAB4FAQCsAAYABgAeBQEANSgBAAYAHgUBAMkDHgUGAAEAAQDVAAYAHgUeBQEAoRYeBQYAAQABAAAAAQABAAEAAQAAAAAAAAAAAAAAAAD/fw==]'

# Zizï Skyhoof
# Tab 1
zizi_specter = '[&D1sDPQkBAAEAAQABAAwAGAURBhEGAQAjABgFEQYBAAEA/AABABEGGAUYBdIDGAURBgEAAQALAAEAEQYRBgEAohYYBREGAQABAHwAAQABAAEAAQDjE6APLzIwMjIyNDL+fg==]'

# Tab 3
zizi = '[&D1sDPQkBAAEAAQABAAwAGAURBhEGAQAjABgFEQYBAAEA/AABABEGGAUYBdIDGAURBgEAAQALAAEAEQYRBgEAohYYBREGAQABAHwAAQABAAEAAQDjE6APPBI8Ej0SAAD+fg==]'
# Armor only
zizi_armor_only = '[&DwAAPQkBAAEAAQABAAwAGAURBhEGAQAjABgFEQYBAAEA/AABABEGGAUYBdIDGAURBgEAAQALAAEAEQYRBgEAohYYBREGAQABAAAAAQABAAEAAQAAAAAAAAAAAAAAAAD/fw==]'

# Empty template
empty = '[&DwAAAAABAAEAAQABAAAAAQABAAEAAQAAAAEAAQABAAEAAAABAAEAAQABAAAAAQABAAEAAQAAAAEAAQABAAEAAAABAAEAAQABAAAAAQABAAEAAQAAAAAAAAAAAAAAAAD/fw==]'
