name: Release CLI

on:
  push:
    tags:
      - "gw2fashionista-cli-v*"

jobs:
  create-github-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          draft: true

  release-cli:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: ".exe"
    runs-on: ${{ matrix.os }}
    needs: create-github-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build CLI
        run: cargo build --release --target ${{ matrix.target }}

      - name: Extract version
        id: version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/gw2fashionista-cli-v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename binary
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/gw2fashionista-cli${{ matrix.extension }} \
            gw2fashionista-cli-${{ steps.version.outputs.version }}-${{ matrix.target }}${{ matrix.extension }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v3
        with:
          files: gw2fashionista-cli-${{ steps.version.outputs.version }}-${{ matrix.target }}${{ matrix.extension }}
          draft: true
